version: "2.2"

networks:
  main-network:
    driver: bridge
volumes:
  log-data:

services:
  db:
    container_name: pg-db
    image: 'postgres:10'
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - main-network
