/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.records;


import example.jooq.databases.tables.A;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ARecord extends TableRecordImpl<ARecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mydb.a.f1</code>.
     */
    public ARecord setF1(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mydb.a.f1</code>.
     */
    public Integer getF1() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mydb.a.f2</code>.
     */
    public ARecord setF2(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mydb.a.f2</code>.
     */
    public Integer getF2() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return A.A.F1;
    }

    @Override
    public Field<Integer> field2() {
        return A.A.F2;
    }

    @Override
    public Integer component1() {
        return getF1();
    }

    @Override
    public Integer component2() {
        return getF2();
    }

    @Override
    public Integer value1() {
        return getF1();
    }

    @Override
    public Integer value2() {
        return getF2();
    }

    @Override
    public ARecord value1(Integer value) {
        setF1(value);
        return this;
    }

    @Override
    public ARecord value2(Integer value) {
        setF2(value);
        return this;
    }

    @Override
    public ARecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ARecord
     */
    public ARecord() {
        super(A.A);
    }

    /**
     * Create a detached, initialised ARecord
     */
    public ARecord(Integer f1, Integer f2) {
        super(A.A);

        setF1(f1);
        setF2(f2);
    }
}
