/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.records;


import example.jooq.databases.tables.T1;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T1Record extends TableRecordImpl<T1Record> implements Record2<String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mydb.t1.val</code>.
     */
    public T1Record setVal(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>mydb.t1.val</code>.
     */
    public String getVal() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mydb.t1.created_time</code>.
     */
    public T1Record setCreatedTime(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>mydb.t1.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, LocalDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return T1.T1.VAL;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return T1.T1.CREATED_TIME;
    }

    @Override
    public String component1() {
        return getVal();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedTime();
    }

    @Override
    public String value1() {
        return getVal();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedTime();
    }

    @Override
    public T1Record value1(String value) {
        setVal(value);
        return this;
    }

    @Override
    public T1Record value2(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public T1Record values(String value1, LocalDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T1Record
     */
    public T1Record() {
        super(T1.T1);
    }

    /**
     * Create a detached, initialised T1Record
     */
    public T1Record(String val, LocalDateTime createdTime) {
        super(T1.T1);

        setVal(val);
        setCreatedTime(createdTime);
    }
}
