server:
  port: 9091


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?socketTimeout=90
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 0
      connection-timeout: 50000
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect