/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.routines;


import example.jooq.databases.Mydb;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Idata extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public Idata() {
        super("idata", Mydb.MYDB);
    }
}
