/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases.tables;


import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.ARecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class A extends TableImpl<ARecord> {

    private static final long serialVersionUID = -1062418018;

    /**
     * The reference instance of <code>mydb.a</code>
     */
    public static final A A = new A();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ARecord> getRecordType() {
        return ARecord.class;
    }

    /**
     * The column <code>mydb.a.f1</code>.
     */
    public final TableField<ARecord, Integer> F1 = createField("f1", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>mydb.a.f2</code>.
     */
    public final TableField<ARecord, Integer> F2 = createField("f2", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>mydb.a</code> table reference
     */
    public A() {
        this("a", null);
    }

    /**
     * Create an aliased <code>mydb.a</code> table reference
     */
    public A(String alias) {
        this(alias, A);
    }

    private A(String alias, Table<ARecord> aliased) {
        this(alias, aliased, null);
    }

    private A(String alias, Table<ARecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public A as(String alias) {
        return new A(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public A rename(String name) {
        return new A(name, null);
    }
}
