/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables;


import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.BRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B extends TableImpl<BRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb.b</code>
     */
    public static final B B = new B();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BRecord> getRecordType() {
        return BRecord.class;
    }

    /**
     * The column <code>mydb.b.f1</code>.
     */
    public final TableField<BRecord, Integer> F1 = createField(DSL.name("f1"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>mydb.b.f2</code>.
     */
    public final TableField<BRecord, Integer> F2 = createField(DSL.name("f2"), SQLDataType.INTEGER, this, "");

    private B(Name alias, Table<BRecord> aliased) {
        this(alias, aliased, null);
    }

    private B(Name alias, Table<BRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mydb.b</code> table reference
     */
    public B(String alias) {
        this(DSL.name(alias), B);
    }

    /**
     * Create an aliased <code>mydb.b</code> table reference
     */
    public B(Name alias) {
        this(alias, B);
    }

    /**
     * Create a <code>mydb.b</code> table reference
     */
    public B() {
        this(DSL.name("b"), null);
    }

    public <O extends Record> B(Table<O> child, ForeignKey<O, BRecord> key) {
        super(child, key, B);
    }

    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    @Override
    public B as(String alias) {
        return new B(DSL.name(alias), this);
    }

    @Override
    public B as(Name alias) {
        return new B(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B rename(String name) {
        return new B(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B rename(Name name) {
        return new B(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
