/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables;


import example.jooq.databases.Keys;
import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.TRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T extends TableImpl<TRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb.t</code>
     */
    public static final T T = new T();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRecord> getRecordType() {
        return TRecord.class;
    }

    /**
     * The column <code>mydb.t.id</code>.
     */
    public final TableField<TRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mydb.t.c</code>.
     */
    public final TableField<TRecord, Integer> C = createField(DSL.name("c"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>mydb.t.d</code>.
     */
    public final TableField<TRecord, Integer> D = createField(DSL.name("d"), SQLDataType.INTEGER, this, "");

    private T(Name alias, Table<TRecord> aliased) {
        this(alias, aliased, null);
    }

    private T(Name alias, Table<TRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mydb.t</code> table reference
     */
    public T(String alias) {
        this(DSL.name(alias), T);
    }

    /**
     * Create an aliased <code>mydb.t</code> table reference
     */
    public T(Name alias) {
        this(alias, T);
    }

    /**
     * Create a <code>mydb.t</code> table reference
     */
    public T() {
        this(DSL.name("t"), null);
    }

    public <O extends Record> T(Table<O> child, ForeignKey<O, TRecord> key) {
        super(child, key, T);
    }

    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    @Override
    public Identity<TRecord, Integer> getIdentity() {
        return (Identity<TRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TRecord> getPrimaryKey() {
        return Keys.KEY_T_PRIMARY;
    }

    @Override
    public List<UniqueKey<TRecord>> getKeys() {
        return Arrays.<UniqueKey<TRecord>>asList(Keys.KEY_T_PRIMARY, Keys.KEY_T_C);
    }

    @Override
    public T as(String alias) {
        return new T(DSL.name(alias), this);
    }

    @Override
    public T as(Name alias) {
        return new T(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T rename(String name) {
        return new T(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T rename(Name name) {
        return new T(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
