/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases.tables;


import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.T1Record;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T1 extends TableImpl<T1Record> {

    private static final long serialVersionUID = -1529131248;

    /**
     * The reference instance of <code>mydb.t1</code>
     */
    public static final T1 T1 = new T1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T1Record> getRecordType() {
        return T1Record.class;
    }

    /**
     * The column <code>mydb.t1.val</code>.
     */
    public final TableField<T1Record, String> VAL = createField("val", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>mydb.t1.created_time</code>.
     */
    public final TableField<T1Record, Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>mydb.t1</code> table reference
     */
    public T1() {
        this("t1", null);
    }

    /**
     * Create an aliased <code>mydb.t1</code> table reference
     */
    public T1(String alias) {
        this(alias, T1);
    }

    private T1(String alias, Table<T1Record> aliased) {
        this(alias, aliased, null);
    }

    private T1(String alias, Table<T1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T1 as(String alias) {
        return new T1(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T1 rename(String name) {
        return new T1(name, null);
    }
}
