/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables;


import example.jooq.databases.Indexes;
import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.T1Record;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T1 extends TableImpl<T1Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb.t1</code>
     */
    public static final T1 T1 = new T1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T1Record> getRecordType() {
        return T1Record.class;
    }

    /**
     * The column <code>mydb.t1.val</code>.
     */
    public final TableField<T1Record, String> VAL = createField(DSL.name("val"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>mydb.t1.created_time</code>.
     */
    public final TableField<T1Record, LocalDateTime> CREATED_TIME = createField(DSL.name("created_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private T1(Name alias, Table<T1Record> aliased) {
        this(alias, aliased, null);
    }

    private T1(Name alias, Table<T1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mydb.t1</code> table reference
     */
    public T1(String alias) {
        this(DSL.name(alias), T1);
    }

    /**
     * Create an aliased <code>mydb.t1</code> table reference
     */
    public T1(Name alias) {
        this(alias, T1);
    }

    /**
     * Create a <code>mydb.t1</code> table reference
     */
    public T1() {
        this(DSL.name("t1"), null);
    }

    public <O extends Record> T1(Table<O> child, ForeignKey<O, T1Record> key) {
        super(child, key, T1);
    }

    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T1_IDX_T1);
    }

    @Override
    public T1 as(String alias) {
        return new T1(DSL.name(alias), this);
    }

    @Override
    public T1 as(Name alias) {
        return new T1(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T1 rename(String name) {
        return new T1(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T1 rename(Name name) {
        return new T1(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
