/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables;


import example.jooq.databases.Keys;
import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.T2Record;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T2 extends TableImpl<T2Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb.t2</code>
     */
    public static final T2 T2 = new T2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<T2Record> getRecordType() {
        return T2Record.class;
    }

    /**
     * The column <code>mydb.t2.id</code>.
     */
    public final TableField<T2Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mydb.t2.c</code>.
     */
    public final TableField<T2Record, Integer> C = createField(DSL.name("c"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>mydb.t2.d</code>.
     */
    public final TableField<T2Record, Integer> D = createField(DSL.name("d"), SQLDataType.INTEGER, this, "");

    private T2(Name alias, Table<T2Record> aliased) {
        this(alias, aliased, null);
    }

    private T2(Name alias, Table<T2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mydb.t2</code> table reference
     */
    public T2(String alias) {
        this(DSL.name(alias), T2);
    }

    /**
     * Create an aliased <code>mydb.t2</code> table reference
     */
    public T2(Name alias) {
        this(alias, T2);
    }

    /**
     * Create a <code>mydb.t2</code> table reference
     */
    public T2() {
        this(DSL.name("t2"), null);
    }

    public <O extends Record> T2(Table<O> child, ForeignKey<O, T2Record> key) {
        super(child, key, T2);
    }

    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    @Override
    public Identity<T2Record, Integer> getIdentity() {
        return (Identity<T2Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<T2Record> getPrimaryKey() {
        return Keys.KEY_T2_PRIMARY;
    }

    @Override
    public List<UniqueKey<T2Record>> getKeys() {
        return Arrays.<UniqueKey<T2Record>>asList(Keys.KEY_T2_PRIMARY, Keys.KEY_T2_C);
    }

    @Override
    public T2 as(String alias) {
        return new T2(DSL.name(alias), this);
    }

    @Override
    public T2 as(Name alias) {
        return new T2(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T2 rename(String name) {
        return new T2(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T2 rename(Name name) {
        return new T2(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
