/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables;


import example.jooq.databases.Keys;
import example.jooq.databases.Mydb;
import example.jooq.databases.tables.records.WeatherRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weather extends TableImpl<WeatherRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydb.weather</code>
     */
    public static final Weather WEATHER = new Weather();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WeatherRecord> getRecordType() {
        return WeatherRecord.class;
    }

    /**
     * The column <code>mydb.weather.id</code>.
     */
    public final TableField<WeatherRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>mydb.weather.temperature</code>.
     */
    public final TableField<WeatherRecord, Double> TEMPERATURE = createField(DSL.name("temperature"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>mydb.weather.description</code>.
     */
    public final TableField<WeatherRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>mydb.weather.created_time</code>.
     */
    public final TableField<WeatherRecord, LocalDateTime> CREATED_TIME = createField(DSL.name("created_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>mydb.weather.updated_time</code>.
     */
    public final TableField<WeatherRecord, LocalDateTime> UPDATED_TIME = createField(DSL.name("updated_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Weather(Name alias, Table<WeatherRecord> aliased) {
        this(alias, aliased, null);
    }

    private Weather(Name alias, Table<WeatherRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mydb.weather</code> table reference
     */
    public Weather(String alias) {
        this(DSL.name(alias), WEATHER);
    }

    /**
     * Create an aliased <code>mydb.weather</code> table reference
     */
    public Weather(Name alias) {
        this(alias, WEATHER);
    }

    /**
     * Create a <code>mydb.weather</code> table reference
     */
    public Weather() {
        this(DSL.name("weather"), null);
    }

    public <O extends Record> Weather(Table<O> child, ForeignKey<O, WeatherRecord> key) {
        super(child, key, WEATHER);
    }

    @Override
    public Schema getSchema() {
        return Mydb.MYDB;
    }

    @Override
    public Identity<WeatherRecord, Long> getIdentity() {
        return (Identity<WeatherRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WeatherRecord> getPrimaryKey() {
        return Keys.KEY_WEATHER_PRIMARY;
    }

    @Override
    public List<UniqueKey<WeatherRecord>> getKeys() {
        return Arrays.<UniqueKey<WeatherRecord>>asList(Keys.KEY_WEATHER_PRIMARY);
    }

    @Override
    public Weather as(String alias) {
        return new Weather(DSL.name(alias), this);
    }

    @Override
    public Weather as(Name alias) {
        return new Weather(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Weather rename(String name) {
        return new Weather(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Weather rename(Name name) {
        return new Weather(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Double, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
