/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases;


import example.jooq.databases.tables.A;
import example.jooq.databases.tables.Account;
import example.jooq.databases.tables.T1;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in mydb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index A_F1 = Internal.createIndex(DSL.name("f1"), A.A, new OrderField[] { A.A.F1 }, false);
    public static final Index T1_IDX_T1 = Internal.createIndex(DSL.name("idx_t1"), T1.T1, new OrderField[] { T1.T1.VAL }, false);
    public static final Index ACCOUNT_IX_ACCOUNT_EMAIL = Internal.createIndex(DSL.name("ix_account_email"), Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.EMAIL }, false);
    public static final Index ACCOUNT_IX_ACCOUNT_PHONE_NUMBER = Internal.createIndex(DSL.name("ix_account_phone_number"), Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.PHONE_NUMBER }, false);
}
