/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases;


import example.jooq.databases.tables.A;
import example.jooq.databases.tables.Account;
import example.jooq.databases.tables.Author;
import example.jooq.databases.tables.AuthorBook;
import example.jooq.databases.tables.B;
import example.jooq.databases.tables.Book;
import example.jooq.databases.tables.T;
import example.jooq.databases.tables.T1;
import example.jooq.databases.tables.T2;
import example.jooq.databases.tables.Weather;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydb extends SchemaImpl {

    private static final long serialVersionUID = -1180455220;

    /**
     * The reference instance of <code>mydb</code>
     */
    public static final Mydb MYDB = new Mydb();

    /**
     * The table <code>mydb.a</code>.
     */
    public final A A = example.jooq.databases.tables.A.A;

    /**
     * The table <code>mydb.account</code>.
     */
    public final Account ACCOUNT = example.jooq.databases.tables.Account.ACCOUNT;

    /**
     * The table <code>mydb.author</code>.
     */
    public final Author AUTHOR = example.jooq.databases.tables.Author.AUTHOR;

    /**
     * The table <code>mydb.author_book</code>.
     */
    public final AuthorBook AUTHOR_BOOK = example.jooq.databases.tables.AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>mydb.b</code>.
     */
    public final B B = example.jooq.databases.tables.B.B;

    /**
     * The table <code>mydb.book</code>.
     */
    public final Book BOOK = example.jooq.databases.tables.Book.BOOK;

    /**
     * The table <code>mydb.t</code>.
     */
    public final T T = example.jooq.databases.tables.T.T;

    /**
     * The table <code>mydb.t1</code>.
     */
    public final T1 T1 = example.jooq.databases.tables.T1.T1;

    /**
     * The table <code>mydb.t2</code>.
     */
    public final T2 T2 = example.jooq.databases.tables.T2.T2;

    /**
     * The table <code>mydb.weather</code>.
     */
    public final Weather WEATHER = example.jooq.databases.tables.Weather.WEATHER;

    /**
     * No further instances allowed
     */
    private Mydb() {
        super("mydb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            A.A,
            Account.ACCOUNT,
            Author.AUTHOR,
            AuthorBook.AUTHOR_BOOK,
            B.B,
            Book.BOOK,
            T.T,
            T1.T1,
            T2.T2,
            Weather.WEATHER);
    }
}
