/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases;


import example.jooq.databases.routines.Idata;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in mydb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>mydb.idata</code>
     */
    public static void idata(
          Configuration configuration
    ) {
        Idata p = new Idata();

        p.execute(configuration);
    }
}
