spring:
  datasource:
    username: root
    password: 19950209
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 50000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
server:
  port: 8099
  compression:
    enabled: true