/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class A implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer f1;
    private final Integer f2;

    public A(A value) {
        this.f1 = value.f1;
        this.f2 = value.f2;
    }

    public A(
        Integer f1,
        Integer f2
    ) {
        this.f1 = f1;
        this.f2 = f2;
    }

    /**
     * Getter for <code>mydb.a.f1</code>.
     */
    public Integer getF1() {
        return this.f1;
    }

    /**
     * Getter for <code>mydb.a.f2</code>.
     */
    public Integer getF2() {
        return this.f2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("A (");

        sb.append(f1);
        sb.append(", ").append(f2);

        sb.append(")");
        return sb.toString();
    }
}
