/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -1825618804;

    private String    id;
    private String    email;
    private String    name;
    private String    phoneNumber;
    private Byte      confirmedAndActive;
    private Timestamp memberSince;
    private String    passwordHash;
    private String    photoUrl;
    private Byte      support;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.email = value.email;
        this.name = value.name;
        this.phoneNumber = value.phoneNumber;
        this.confirmedAndActive = value.confirmedAndActive;
        this.memberSince = value.memberSince;
        this.passwordHash = value.passwordHash;
        this.photoUrl = value.photoUrl;
        this.support = value.support;
    }

    public Account(
        String    id,
        String    email,
        String    name,
        String    phoneNumber,
        Byte      confirmedAndActive,
        Timestamp memberSince,
        String    passwordHash,
        String    photoUrl,
        Byte      support
    ) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.confirmedAndActive = confirmedAndActive;
        this.memberSince = memberSince;
        this.passwordHash = passwordHash;
        this.photoUrl = photoUrl;
        this.support = support;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Byte getConfirmedAndActive() {
        return this.confirmedAndActive;
    }

    public void setConfirmedAndActive(Byte confirmedAndActive) {
        this.confirmedAndActive = confirmedAndActive;
    }

    public Timestamp getMemberSince() {
        return this.memberSince;
    }

    public void setMemberSince(Timestamp memberSince) {
        this.memberSince = memberSince;
    }

    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getPhotoUrl() {
        return this.photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public Byte getSupport() {
        return this.support;
    }

    public void setSupport(Byte support) {
        this.support = support;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(name);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(confirmedAndActive);
        sb.append(", ").append(memberSince);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(photoUrl);
        sb.append(", ").append(support);

        sb.append(")");
        return sb.toString();
    }
}
