/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBook implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer authorId;
    private final Integer bookId;

    public AuthorBook(AuthorBook value) {
        this.authorId = value.authorId;
        this.bookId = value.bookId;
    }

    public AuthorBook(
        Integer authorId,
        Integer bookId
    ) {
        this.authorId = authorId;
        this.bookId = bookId;
    }

    /**
     * Getter for <code>mydb.author_book.author_id</code>.
     */
    public Integer getAuthorId() {
        return this.authorId;
    }

    /**
     * Getter for <code>mydb.author_book.book_id</code>.
     */
    public Integer getBookId() {
        return this.bookId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorBook (");

        sb.append(authorId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
