/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B implements Serializable {

    private static final long serialVersionUID = -1388586727;

    private Integer f1;
    private Integer f2;

    public B() {}

    public B(B value) {
        this.f1 = value.f1;
        this.f2 = value.f2;
    }

    public B(
        Integer f1,
        Integer f2
    ) {
        this.f1 = f1;
        this.f2 = f2;
    }

    public Integer getF1() {
        return this.f1;
    }

    public void setF1(Integer f1) {
        this.f1 = f1;
    }

    public Integer getF2() {
        return this.f2;
    }

    public void setF2(Integer f2) {
        this.f2 = f2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("B (");

        sb.append(f1);
        sb.append(", ").append(f2);

        sb.append(")");
        return sb.toString();
    }
}
