/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  title;

    public Book(Book value) {
        this.id = value.id;
        this.title = value.title;
    }

    public Book(
        Integer id,
        String  title
    ) {
        this.id = id;
        this.title = title;
    }

    /**
     * Getter for <code>mydb.book.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>mydb.book.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
