/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T implements Serializable {

    private static final long serialVersionUID = -1402980308;

    private Integer id;
    private Integer c;
    private Integer d;

    public T() {}

    public T(T value) {
        this.id = value.id;
        this.c = value.c;
        this.d = value.d;
    }

    public T(
        Integer id,
        Integer c,
        Integer d
    ) {
        this.id = id;
        this.c = c;
        this.d = d;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getC() {
        return this.c;
    }

    public void setC(Integer c) {
        this.c = c;
    }

    public Integer getD() {
        return this.d;
    }

    public void setD(Integer d) {
        this.d = d;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("T (");

        sb.append(id);
        sb.append(", ").append(c);
        sb.append(", ").append(d);

        sb.append(")");
        return sb.toString();
    }
}
