/*
 * This file is generated by jOOQ.
*/
package example.jooq.databases.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T1 implements Serializable {

    private static final long serialVersionUID = -769206714;

    private String    val;
    private Timestamp createdTime;

    public T1() {}

    public T1(T1 value) {
        this.val = value.val;
        this.createdTime = value.createdTime;
    }

    public T1(
        String    val,
        Timestamp createdTime
    ) {
        this.val = val;
        this.createdTime = createdTime;
    }

    public String getVal() {
        return this.val;
    }

    public void setVal(String val) {
        this.val = val;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("T1 (");

        sb.append(val);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
