/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T2 implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer c;
    private final Integer d;

    public T2(T2 value) {
        this.id = value.id;
        this.c = value.c;
        this.d = value.d;
    }

    public T2(
        Integer id,
        Integer c,
        Integer d
    ) {
        this.id = id;
        this.c = c;
        this.d = d;
    }

    /**
     * Getter for <code>mydb.t2.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>mydb.t2.c</code>.
     */
    public Integer getC() {
        return this.c;
    }

    /**
     * Getter for <code>mydb.t2.d</code>.
     */
    public Integer getD() {
        return this.d;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("T2 (");

        sb.append(id);
        sb.append(", ").append(c);
        sb.append(", ").append(d);

        sb.append(")");
        return sb.toString();
    }
}
