/*
 * This file is generated by jOOQ.
 */
package example.jooq.databases.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Weather implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final Double        temperature;
    private final String        description;
    private final LocalDateTime createdTime;
    private final LocalDateTime updatedTime;

    public Weather(Weather value) {
        this.id = value.id;
        this.temperature = value.temperature;
        this.description = value.description;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
    }

    public Weather(
        Long          id,
        Double        temperature,
        String        description,
        LocalDateTime createdTime,
        LocalDateTime updatedTime
    ) {
        this.id = id;
        this.temperature = temperature;
        this.description = description;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for <code>mydb.weather.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>mydb.weather.temperature</code>.
     */
    public Double getTemperature() {
        return this.temperature;
    }

    /**
     * Getter for <code>mydb.weather.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>mydb.weather.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Getter for <code>mydb.weather.updated_time</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Weather (");

        sb.append(id);
        sb.append(", ").append(temperature);
        sb.append(", ").append(description);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
