spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  security:
    user:
      name: client
      password: client
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
